# Week 3 Summary

## Abstract Class
* The abstract keyword enables you to create incomplete classes.
* Classes can be declared as abstract using the `abstract` keyword before the class definition.

## Interface
* Interfaces contain member definitions without implementation.
* Useful for defining contracts between different types.
* Members are implicitly public.

## Interface vs. Abstract Class
* An abstract class may have member variables and non-abstract methods or properties.
* A class or abstract class can inherit from one class or abstract class.
* A class may implement one or more interfaces.
* An interface can extend other interfaces.
* An abstract class may have non-public methods and properties.
* An abstract class may have constants, static methods, and static members.
* An abstract class may have constructors.
* An interface cannot have these features.

## Static Class
* A static class cannot be instantiated.
* No `new` operator can be used for a static class.

## Extension Methods
* Provide the illusion of adding new methods to existing classes.
* Extension methods are static methods callable as if they were instance methods.

## Partial Class
* Class code divided into separate files.
* Parts of a partial class must be marked with the `partial` keyword.

## Partial Methods
* A class or struct may contain a partial method.
* One part contains the method signature, and implementation can be in the same or another part.

## Property
* Provides a mechanism to read, write, or compute the value of a private field.
* Accessors are special methods for properties.

## Indexer
* Allows instances of a class or struct to be indexed like arrays.
* Similar to properties but with parameters in accessors.

## Exceptional Handling
* Uses `try`, `catch`, and `finally` keywords.
* Handles unexpected situations during program execution.
* Exceptions can be generated by the CLR, .NET, or third-party libraries.

## Enum
* A value type defined by a set of named constants.
* Defined using the `enum` keyword.

## Attributes
* Associates metadata with code entities.
* Queryable at runtime using reflection.

## Extension Methods (Repeated)
* Extend existing types without creating a new derived type.
* Static methods callable as instance methods.

## Anonymous Type (Repeated)
* Encapsulates a set of read-only properties into a single object.
* Type name generated by the compiler.

## Var and Dynamic
* Statically typed languages validate syntax during compilation (e.g., C# and Java).
* Dynamically typed languages validate syntax at runtime (e.g., JavaScript).

## Delegates
* Represents references to methods with a specific parameter list and return type.
* Can associate with any method with a compatible signature.

## Events
* Enable a class or object to notify others when something of interest occurs.
* Publisher sends the event, and subscribers handle it.
